#pragma config(Sensor, S1,     MSLSA,          sensorEV3_GenericI2C)
#pragma config(Sensor, S2,     COLORR,         sensorEV3_Color, modeEV3Color_Ambient)
#pragma config(Sensor, S3,     COLORL,         sensorEV3_Color, modeEV3Color_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DEBUG

#include "include/mindsensors-lightsensorarray.h"

enum COLOR_TYPE
{
	BLACK,
	WHITE,
	GREY,
	RED,
	GREEN,
	UNDEFINED
};

typedef struct
{
	long red;
	long green;
	long blue;
} color;

/* struttura contenente i dati dei sensori */
typedef struct
{
	tByteArray lightSensor;
	color colorRight;
	color colorLeft;
} sensor_set;

static sensor_set sensors;

// trasforma i colori RGB ottenuti dal sensore in COLOR_TYPE
enum COLOR_TYPE rgbToColor(color *rgbColor)
{
	if(rgbColor->red < 5 && rgbColor->green < 5 && rgbColor->blue < 5)
		return BLACK;
	else if(rgbColor->red > 30 && rgbColor->green > 30 && rgbColor->blue > 30)
		return WHITE;
	else if(rgbColor->red > 15 && rgbColor->green > 15 && rgbColor->blue > 15)
		return GREY;
	else if(rgbColor->red > 10)
		return RED;
	else if(rgbColor->green > 10)
		return GREEN;
	else
		return UNDEFINED;
}

#ifdef DEBUG
char *colorToString(enum COLOR_TYPE color)
{
	char str[12];

	switch (color)
	{
		case BLACK:
			sprintf(str, "black");
			break;
		case WHITE:
			sprintf(str, "white");
			break;
		case GREY:
			sprintf(str, "grey");
			break;
		case RED:
			sprintf(str, "red");
			break;
		case GREEN:
			sprintf(str, "green");
			break;
		case UNDEFINED:
			sprintf(str, "undefined");
			break;
		default:
			sprintf(str, "error");
			break;
	}

	return &str;
}
#endif

/* thread per leggere i sensori */
task updateSensors()
{
	MSLSAsetEU(MSLSA);
	// inizializza sensore multibarra
	MSLSAinit(MSLSA);

	while(true)
	{
		// leggi sensore multibarra
		MSLSAreadSensors(MSLSA, &sensors.lightSensor[0]);
		for(int i = 0; i < 8; i++)
		{
			#ifdef DEBUG
				writeDebugStream("%d ", sensors.lightSensor[i]);
			#endif
		}
		writeDebugStream("\n");

//		sensors.colorRight = SensorValue(COLORR);
//		sensors.colorLeft = SensorValue(COLORL);
		getColorRGB(COLORR, sensors.colorRight.red,
												sensors.colorRight.green,
												sensors.colorRight.blue);

		getColorRGB(COLORL, sensors.colorLeft.red,
												sensors.colorLeft.green,
												sensors.colorLeft.blue);

		sleep(500);

		/*
		writeDebugStream("Right color R: %d, G: %d, B: %d\n", sensors.colorRight.red,
																													sensors.colorRight.green,
																													sensors.colorRight.blue);
		//writeDebugStream("Color right: %d, Color left: %d\n", sensors.colorRight, sensors.colorLeft);
		writeDebugStream("Right color L: %d, G: %d, B: %d\n", sensors.colorLeft.red,
																													sensors.colorLeft.green,
																													sensors.colorLeft.blue);
		*/
		enum COLOR_TYPE colorLeftValue = rgbToColor(sensors.colorLeft);

		#ifdef DEBUG
			writeDebugStream("Color left: %s\n", colorToString(colorLeftValue));
		#endif
	}
}

task main()
{
	startTask(updateSensors);

	sleep(20000);
}
