#pragma config(Sensor, S1,     MSLSA,          sensorEV3_GenericI2C)										// Lo slot 1 è usato per il sensore multibarra
#pragma config(Sensor, S2,     COLORR,         sensorEV3_Color, modeEV3Color_RGB_Raw)		// Lo slot 2 è usato per il sensore di colore destro
#pragma config(Sensor, S3,     COLORL,         sensorEV3_Color, modeEV3Color_RGB_Raw)		// lo slot 3 è usato per il sensore di colore sinistro
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "include/mindsensors-lightsensorarray.h"

typedef struct
{
	tByteArray lightSensor;
	short colorRight;
	short colorLeft;
} sensor_set;

static sensor_set sensors;

task updateSensors()
{
	MSLSAsetEU(MSLSA);
	MSLSAinit(MSLSA);

	while(true)
	{
		MSLSAreadSensors(MSLSA, &sensors.lightSensor[0]);
		for(int i = 0; i < 8; i++)
		{
			//writeDebugStream("Sensor %d: %d", i, sensors.lightSensor[i]);
		}
		//writeDebugStream("\n");

		sensors.colorRight = SensorValue(COLORR);
		sensors.colorLeft = SensorValue(COLORL);

		sleep(500);

		writeDebugStream("Color right: %d, Color left: %d\n", sensors.colorRight, sensors.colorLeft);
	}
}

task main()
{
	startTask(updateSensors);

	sleep(20000);
}
